In [ ]:
import matplotlib.pyplot as plt

plt.figure()
plt.plot([1,2,3],[10,20,30])

plt.savefig("reports/charts/nav_trend.png")
plt.show()

In [ ]:
pd.read_sql("""
SELECT scheme_name, MAX(nav)
FROM nav_history
GROUP BY scheme_name
""", conn)

        scheme_name   MAX(nav)
0     Axis Bluechip  6158.9665
1    ICICI Bluechip   113.6849
2    Kotak Bluechip   281.1083
3  Nippon Large Cap   106.1272
4      SBI Bluechip   161.3775

In [ ]:
pd.read_sql("SELECT * FROM nav_history LIMIT 5", conn)

         date       nav   scheme_name  scheme_code
0  02-06-2026  104.7663  SBI Bluechip       119551
1  01-06-2026  104.7025  SBI Bluechip       119551
2  29-05-2026  104.6570  SBI Bluechip       119551
3  27-05-2026  104.5833  SBI Bluechip       119551
4  26-05-2026  104.5269  SBI Bluechip       119551

In [ ]:
conn = sqlite3.connect("mutual_fund.db")

df.to_sql("nav_history", conn, if_exists="replace", index=False)

16712

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
df = pd.read_csv(r"d:\mutual_fund_analytics\data\raw\multi_scheme_nav.csv")
df.head()

         date       nav   scheme_name  scheme_code
0  02-06-2026  104.7663  SBI Bluechip       119551
1  01-06-2026  104.7025  SBI Bluechip       119551
2  29-05-2026  104.6570  SBI Bluechip       119551
3  27-05-2026  104.5833  SBI Bluechip       119551
4  26-05-2026  104.5269  SBI Bluechip       119551