In [2]:
import os

print(os.listdir())

['01_data_ingestion.ipynb', '02_data_cleaning.ipynb', '03_load_sqlite.ipynb', '03_sql_database.ipynb', 'bluestock_mf.db', 'DATA DICTIONARY', 'eda.ipynb', 'mutual_fund.db', 'notebooks', 'Performance_Analytics.ipynb', 'reports']

In [1]:
import os

print("Current Folder:")
print(os.getcwd())

print("\nFiles:")
for file in os.listdir():
    print(file)

Current Folder:
d:\mutual_fund_analytics\notebooks

Files:
01_data_ingestion.ipynb
02_data_cleaning.ipynb
03_load_sqlite.ipynb
03_sql_database.ipynb
bluestock_mf.db
DATA DICTIONARY
eda.ipynb
mutual_fund.db
notebooks
Performance_Analytics.ipynb
reports

In [3]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("mutual_fund.db")

query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

tables = pd.read_sql(query, conn)
tables

          name
0  nav_history

In [5]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("../mutual_fund.db")

df = pd.read_sql("SELECT * FROM nav_history LIMIT 5", conn)

print(df.columns.tolist())
df.head()

DatabaseError: Execution failed on sql 'SELECT * FROM nav_history LIMIT 5': no such table: nav_history

In [6]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("../mutual_fund.db")

tables = pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table'
""", conn)

print(tables)

Empty DataFrame
Columns: [name]
Index: []

In [10]:
import os

for root, dirs, files in os.walk(".."):
    for file in files:
        if file.endswith(".db"):
            print(os.path.join(root, file))

..\bluestock_mf.db
..\mutual_fund.db
..\notebooks\bluestock_mf.db
..\notebooks\mutual_fund.db

In [13]:
import os

for root, dirs, files in os.walk(".."):
    for file in files:
        if file.endswith(".db"):
            path = os.path.join(root, file)
            print(path, "->", os.path.getsize(path), "bytes")

..\bluestock_mf.db -> 0 bytes
..\mutual_fund.db -> 0 bytes
..\notebooks\bluestock_mf.db -> 16384 bytes
..\notebooks\mutual_fund.db -> 765952 bytes

In [14]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("../bluestock_mf.db")

tables = pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table'
""", conn)

print(tables)

Empty DataFrame
Columns: [name]
Index: []

In [16]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("mutual_fund.db")

tables = pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table'
""", conn)

print(tables)

          name
0  nav_history

In [18]:
for table in tables['name']:
    print("\nTABLE:", table)

    df = pd.read_sql(
        f"SELECT * FROM {table} LIMIT 5",
        conn
    )

    print(df.columns.tolist())

TABLE: nav_history
['date', 'nav', 'scheme_name', 'scheme_code']

In [20]:
import pandas as pd

df = pd.read_sql("SELECT * FROM nav_history LIMIT 5", conn)

print(df.columns.tolist())
df.head()

['date', 'nav', 'scheme_name', 'scheme_code']

         date       nav   scheme_name  scheme_code
0  02-06-2026  104.7663  SBI Bluechip       119551
1  01-06-2026  104.7025  SBI Bluechip       119551
2  29-05-2026  104.6570  SBI Bluechip       119551
3  27-05-2026  104.5833  SBI Bluechip       119551
4  26-05-2026  104.5269  SBI Bluechip       119551

In [22]:
import pandas as pd

nav_df = pd.read_sql(
    "SELECT date, nav, scheme_name FROM nav_history",
    conn
)

nav_df.head()

         date       nav   scheme_name
0  02-06-2026  104.7663  SBI Bluechip
1  01-06-2026  104.7025  SBI Bluechip
2  29-05-2026  104.6570  SBI Bluechip
3  27-05-2026  104.5833  SBI Bluechip
4  26-05-2026  104.5269  SBI Bluechip

In [24]:
nav_df['date'] = pd.to_datetime(
    nav_df['date'],
    format='%d-%m-%Y'
)

nav_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16712 entries, 0 to 16711
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         16712 non-null  datetime64[us]
 1   nav          16712 non-null  float64
 2   scheme_name  16712 non-null  str
dtypes: datetime64[us](1), float64(1), str(1)
memory usage: 391.8 KB

In [26]:
print(nav_df['scheme_name'].nunique())

5

In [28]:
print(nav_df['scheme_name'].unique())

<StringArray>
[    'SBI Bluechip',   'ICICI Bluechip', 'Nippon Large Cap',
    'Axis Bluechip',   'Kotak Bluechip']
Length: 5, dtype: str

In [29]:
import os

folder_path = "data/raw"   # change this if your folder is different

csv_files = [f for f in os.listdir(folder_path) if f.endswith(".csv")]

print("CSV files found:")
for file in csv_files:
    print(file)

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'data/raw'

In [1399]:
import os

deliverables = [
    "cagr_comparison.csv",
    "sharpe_ratio.csv",
    "max_drawdown.csv",
    "fund_scorecard.csv"
]

for f in deliverables:
    print(f, os.path.getsize(f), "bytes")

cagr_comparison.csv 393 bytes
sharpe_ratio.csv 180 bytes
max_drawdown.csv 195 bytes
fund_scorecard.csv 519 bytes

In [1400]:
import os

for root, dirs, files in os.walk("."):
    for file in files:
        if "nifty" in file.lower():
            print(os.path.join(root, file))

In [1401]:
import os

files = [
    "cagr_comparison.csv",
    "sharpe_ratio.csv",
    "max_drawdown.csv",
    "fund_scorecard.csv"
]

for f in files:
    print(f, "->", os.path.exists(f))

cagr_comparison.csv -> True
sharpe_ratio.csv -> True
max_drawdown.csv -> True
fund_scorecard.csv -> True

In [1402]:
cagr_table.to_csv("cagr_comparison.csv")
sharpe_df.to_csv("sharpe_ratio.csv")
dd_df.to_csv("max_drawdown.csv")
scorecard.to_csv("fund_scorecard.csv")

In [1403]:
scorecard.to_csv("fund_scorecard.csv")

In [1404]:
print(scorecard.sort_values('Score', ascending=False))

                    CAGR_3Y    Sharpe     MaxDD  CAGR_rank  Sharpe_rank  \
scheme_name
Nippon Large Cap  27.342763  6.470335 -0.884864        0.8          1.0
ICICI Bluechip    32.833869  6.145177 -0.880091        1.0          0.6
Kotak Bluechip    17.492967  6.438055 -0.890988        0.6          0.8
Axis Bluechip     10.800452  2.501252 -0.610454        0.4          0.4
SBI Bluechip       2.221634 -0.978025 -0.366517        0.2          0.2

                  DD_rank  Score
scheme_name
Nippon Large Cap      0.8   86.0
ICICI Bluechip        0.6   80.0
Kotak Bluechip        1.0   74.0
Axis Bluechip         0.4   40.0
SBI Bluechip          0.2   20.0

In [1405]:
print(clean_nav.groupby('scheme_name')['nav'].agg(['min','max']))

                       min         max
scheme_name
Axis Bluechip      23.9920   61.589665
ICICI Bluechip     13.6318  113.684900
Kotak Bluechip     30.5643  281.108300
Nippon Large Cap   12.2191  106.127200
SBI Bluechip      102.2299  161.377500

In [1406]:
scorecard['CAGR_rank'] = scorecard['CAGR_3Y'].rank()
scorecard['Sharpe_rank'] = scorecard['Sharpe'].rank()
scorecard['DD_rank'] = scorecard['MaxDD'].rank(ascending=False)

In [1407]:
scorecard['CAGR_rank'] = scorecard['CAGR_3Y'].rank(
    ascending=True,
    pct=True
)

scorecard['Sharpe_rank'] = scorecard['Sharpe'].rank(
    ascending=True,
    pct=True
)

scorecard['DD_rank'] = scorecard['MaxDD'].rank(
    ascending=False,
    pct=True
)

In [1408]:
nav_pivot = clean_nav.pivot_table(
    index='date',
    columns='scheme_name',
    values='nav'
).sort_index()

returns = nav_pivot.pct_change()

In [1409]:
clean_nav = nav_df.copy()

# Fix Axis
mask = (
    (clean_nav['scheme_name'] == 'Axis Bluechip') &
    (clean_nav['nav'] > 500)
)
clean_nav.loc[mask, 'nav'] = clean_nav.loc[mask, 'nav'] / 100

# Remove invalid NAVs
clean_nav = clean_nav[clean_nav['nav'] > 0]

In [1410]:
scorecard = pd.DataFrame(index=nav_pivot.columns)

scorecard['CAGR_3Y'] = cagr_table['3Y CAGR']
scorecard['Sharpe'] = sharpe_df['Sharpe']
scorecard['MaxDD'] = dd_df['Max_Drawdown']

scorecard['CAGR_rank'] = scorecard['CAGR_3Y'].rank(
    ascending=False,
    pct=True
)

scorecard['Sharpe_rank'] = scorecard['Sharpe'].rank(
    ascending=False,
    pct=True
)

scorecard['DD_rank'] = scorecard['MaxDD'].rank(
    ascending=False,
    pct=True
)

scorecard['Score'] = (
    scorecard['CAGR_rank'] * 50 +
    scorecard['Sharpe_rank'] * 30 +
    scorecard['DD_rank'] * 20
)

scorecard = scorecard.sort_values(
    'Score',
    ascending=False
)

print(scorecard.head())

                    CAGR_3Y    Sharpe     MaxDD  CAGR_rank  Sharpe_rank  \
scheme_name
SBI Bluechip       2.221634 -0.978025 -0.366517        1.0          1.0
Axis Bluechip     10.800452  2.501252 -0.610454        0.8          0.8
Kotak Bluechip    17.492967  6.438055 -0.890988        0.6          0.4
Nippon Large Cap  27.342763  6.470335 -0.884864        0.4          0.2
ICICI Bluechip    32.833869  6.145177 -0.880091        0.2          0.6

                  DD_rank  Score
scheme_name
SBI Bluechip          0.2   84.0
Axis Bluechip         0.4   72.0
Kotak Bluechip        1.0   62.0
Nippon Large Cap      0.8   42.0
ICICI Bluechip        0.6   40.0

In [1411]:
cagr_table.to_csv("cagr_comparison.csv")
sharpe_df.to_csv("sharpe_ratio.csv")
dd_df.to_csv("max_drawdown.csv")
scorecard.to_csv("fund_scorecard.csv")

In [1412]:
max_dd = {}

for fund in nav_pivot.columns:

    nav = nav_pivot[fund].dropna()

    running_max = nav.cummax()

    drawdown = nav / running_max - 1

    max_dd[fund] = drawdown.min()

dd_df = pd.DataFrame.from_dict(
    max_dd,
    orient='index',
    columns=['Max_Drawdown']
)

print(dd_df.sort_values('Max_Drawdown'))

                  Max_Drawdown
Kotak Bluechip       -0.890988
Nippon Large Cap     -0.884864
ICICI Bluechip       -0.880091
Axis Bluechip        -0.610454
SBI Bluechip         -0.366517

In [1413]:
scorecard = pd.DataFrame(index=nav_pivot.columns)

scorecard['CAGR_3Y'] = cagr_table['3Y CAGR']
scorecard['Sharpe'] = sharpe_df['Sharpe']
scorecard['MaxDD'] = dd_df['Max_Drawdown']

scorecard['CAGR_rank'] = scorecard['CAGR_3Y'].rank(pct=True)
scorecard['Sharpe_rank'] = scorecard['Sharpe'].rank(pct=True)
scorecard['DD_rank'] = scorecard['MaxDD'].rank(
    ascending=False,
    pct=True
)

scorecard['Score'] = (
    scorecard['CAGR_rank'] * 50 +
    scorecard['Sharpe_rank'] * 30 +
    scorecard['DD_rank'] * 20
)

scorecard = scorecard.sort_values(
    'Score',
    ascending=False
)

scorecard

,CAGR_3Y,Sharpe,MaxDD,CAGR_rank,Sharpe_rank,DD_rank,Score
scheme_name,,,,,,,
Nippon Large Cap,27.342763,6.470335,-0.884864,0.8,1.0,0.8,86.0
ICICI Bluechip,32.833869,6.145177,-0.880091,1.0,0.6,0.6,80.0
Kotak Bluechip,17.492967,6.438055,-0.890988,0.6,0.8,1.0,74.0
Axis Bluechip,10.800452,2.501252,-0.610454,0.4,0.4,0.4,40.0
SBI Bluechip,2.221634,-0.978025,-0.366517,0.2,0.2,0.2,20.0

In [1414]:
max_dd = {}

for fund in nav_pivot.columns:

    nav = nav_pivot[fund].dropna()

    running_max = nav.cummax()

    drawdown = nav / running_max - 1

    max_dd[fund] = drawdown.min()

dd_df = pd.DataFrame.from_dict(
    max_dd,
    orient='index',
    columns=['Max_Drawdown']
)

dd_df.sort_values('Max_Drawdown')

                  Max_Drawdown
Kotak Bluechip       -0.890988
Nippon Large Cap     -0.884864
ICICI Bluechip       -0.880091
Axis Bluechip        -0.610454
SBI Bluechip         -0.366517

In [1415]:
returns['ICICI Bluechip'].isna().sum()

np.int64(593)

In [1416]:
returns['ICICI Bluechip'].describe()

count    3028.000000
mean        0.146684
std         0.378255
min        -0.873987
25%         0.024571
50%         0.176217
75%         0.363369
max         2.199301
Name: ICICI Bluechip, dtype: float64

In [1417]:
print("Unique Scheme Codes:", nav_df['scheme_code'].nunique())

Unique Scheme Codes: 5

In [1418]:
sharpe_df

                    Sharpe
Axis Bluechip     2.501252
ICICI Bluechip    6.145177
Kotak Bluechip    6.438055
Nippon Large Cap  6.470335
SBI Bluechip     -0.978025

In [1419]:
sortino = {}

for fund in returns.columns:

    r = returns[fund].dropna()

    downside = r[r < 0]

    annual_return = r.mean() * 252

    downside_std = downside.std() * np.sqrt(252)

    sortino[fund] = (
        (annual_return - rf) /
        downside_std
    )

sortino_df = pd.DataFrame.from_dict(
    sortino,
    orient='index',
    columns=['Sortino']
)

sortino_df.sort_values(
    'Sortino',
    ascending=False
)

                   Sortino
Axis Bluechip     9.421417
Kotak Bluechip    9.068560
Nippon Large Cap  6.929818
ICICI Bluechip    6.056734
SBI Bluechip     -1.149677

In [1420]:
scheme_codes = [
    119551,
    120503,
    ...
]

In [1421]:
import numpy as np
import pandas as pd

rf = 0.065

sharpe = {}

for fund in returns.columns:

    r = returns[fund].dropna()

    annual_return = r.mean() * 252
    annual_vol = r.std() * np.sqrt(252)

    sharpe[fund] = (annual_return - rf) / annual_vol

sharpe_df = pd.DataFrame.from_dict(
    sharpe,
    orient='index',
    columns=['Sharpe']
)

sharpe_df = sharpe_df.sort_values(
    'Sharpe',
    ascending=False
)

sharpe_df

                    Sharpe
Nippon Large Cap  6.470335
Kotak Bluechip    6.438055
ICICI Bluechip    6.145177
Axis Bluechip     2.501252
SBI Bluechip     -0.978025

In [1422]:
cagr_table.round(2)

                  1Y CAGR  3Y CAGR  5Y CAGR
scheme_name
Axis Bluechip       87.89    10.80     8.12
ICICI Bluechip     256.16    32.83    45.16
Kotak Bluechip     389.12    17.49    32.85
Nippon Large Cap   270.28    27.34    48.93
SBI Bluechip       -13.97     2.22    -6.05

In [1423]:
rf = 0.065

sharpe = {}

for fund in returns.columns:

    r = returns[fund].dropna()

    annual_return = r.mean() * 252
    annual_vol = r.std() * np.sqrt(252)

    sharpe[fund] = (annual_return - rf) / annual_vol

sharpe_df = pd.DataFrame.from_dict(
    sharpe,
    orient='index',
    columns=['Sharpe']
)

sharpe_df.sort_values('Sharpe', ascending=False)

                    Sharpe
Nippon Large Cap  6.470335
Kotak Bluechip    6.438055
ICICI Bluechip    6.145177
Axis Bluechip     2.501252
SBI Bluechip     -0.978025

In [1424]:
cagr_table = pd.DataFrame(index=nav_pivot.columns)

for fund in nav_pivot.columns:
    cagr_table.loc[fund,'1Y CAGR'] = cagr(nav_pivot[fund],1)
    cagr_table.loc[fund,'3Y CAGR'] = cagr(nav_pivot[fund],3)
    cagr_table.loc[fund,'5Y CAGR'] = cagr(nav_pivot[fund],5)

cagr_table = cagr_table * 100

cagr_table.round(2)

                  1Y CAGR  3Y CAGR  5Y CAGR
scheme_name
Axis Bluechip       87.89    10.80     8.12
ICICI Bluechip     256.16    32.83    45.16
Kotak Bluechip     389.12    17.49    32.85
Nippon Large Cap   270.28    27.34    48.93
SBI Bluechip       -13.97     2.22    -6.05

In [1425]:
import numpy as np

def cagr(series, years):
    series = series.dropna()

    trading_days = years * 252

    if len(series) < trading_days:
        return np.nan

    start = series.iloc[-trading_days]
    end = series.iloc[-1]

    return (end/start)**(1/years) - 1

In [1426]:
nav_pivot.index.to_series().diff().value_counts().head(10)

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [ ]:
print(nav_pivot.index.min())
print(nav_pivot.index.max())

2012-12-31 00:00:00
2026-06-02 00:00:00

In [ ]:
nav_pivot.index.to_series().diff().value_counts().head(10)

date
1 days    2851
3 days     397
2 days     316
4 days      53
5 days       3
Name: count, dtype: int64

In [ ]:
years * 252

NameError: name 'years' is not defined

In [ ]:
years * 12

NameError: name 'years' is not defined

In [ ]:
nav_pivot.tail(12)

scheme_name,Axis Bluechip,ICICI Bluechip,Kotak Bluechip,Nippon Large Cap,SBI Bluechip
date,,,,,
2026-05-18,6148.4847,104.1556,241.2615,97.9372,104.3791
2026-05-19,6149.7598,104.2767,241.6771,98.1289,104.4216
2026-05-20,6147.5856,104.6046,244.7199,98.3933,104.3826
2026-05-21,6142.8808,104.4915,248.8853,98.3781,104.2850
2026-05-22,6142.6380,104.7708,247.8039,98.7497,104.3467
2026-05-25,6144.8478,105.9217,249.2266,99.8047,104.5215
2026-05-26,6144.0004,105.5115,251.2702,99.4356,104.5269
2026-05-27,6146.6118,105.9296,251.2273,99.8092,104.5833
2026-05-29,6151.1139,104.3129,248.6673,98.4656,104.6570
2026-05-31,NaN,104.3083,NaN,NaN,NaN
2026-06-01,6156.7532,103.0948,246.9814,97.1944,104.7025
2026-06-02,6158.9665,103.5959,246.8566,97.4783,104.7663

In [ ]:
print(nav_pivot.index.min())
print(nav_pivot.index.max())

2012-12-31 00:00:00
2026-06-02 00:00:00

In [ ]:
cagr_table.round(2)

                  1Y CAGR  3Y CAGR  5Y CAGR
scheme_name
Axis Bluechip        0.17     0.18     0.26
ICICI Bluechip      -0.54    -0.17    -0.59
Kotak Bluechip       1.97     3.20     2.91
Nippon Large Cap    -0.54    -0.01    -0.50
SBI Bluechip         0.16     0.08    -1.15

In [ ]:
cagr_table.to_csv("cagr_comparison.csv")
sharpe_df.to_csv("sharpe_ratio.csv")
sortino_df.to_csv("sortino_ratio.csv")
dd_df.to_csv("max_drawdown.csv")

In [ ]:
max_dd = {}

for fund in nav_pivot.columns:

    nav = nav_pivot[fund].dropna()

    running_max = nav.cummax()

    drawdown = (
        nav/running_max
    ) - 1

    max_dd[fund] = drawdown.min()

dd_df = pd.DataFrame.from_dict(
    max_dd,
    orient='index',
    columns=['Max_Drawdown']
)

dd_df

                  Max_Drawdown
Axis Bluechip        -0.013924
ICICI Bluechip       -1.000000
Kotak Bluechip       -0.334299
Nippon Large Cap     -0.399608
SBI Bluechip         -0.366517

In [ ]:
sortino = {}

for fund in returns.columns:

    r = returns[fund].dropna()

    downside = r[r < 0]

    annual_return = r.mean() * 12

    downside_std = (
        downside.std()
        * np.sqrt(12)
    )

    sortino[fund] = (
        (annual_return - rf)
        / downside_std
    )

sortino_df = pd.DataFrame.from_dict(
    sortino,
    orient='index',
    columns=['Sortino']
)

sortino_df

                     Sortino
Axis Bluechip     116.874441
ICICI Bluechip           inf
Kotak Bluechip     -1.936144
Nippon Large Cap   -1.962961
SBI Bluechip       -1.886644

In [ ]:
sharpe = {}

for fund in returns.columns:

    r = returns[fund].dropna()

    annual_return = r.mean() * 12
    annual_vol = r.std() * np.sqrt(12)

    sharpe[fund] = (
        (annual_return - rf)
        / annual_vol
    )

sharpe_df = pd.DataFrame.from_dict(
    sharpe,
    orient='index',
    columns=['Sharpe']
)

sharpe_df.sort_values(
    'Sharpe',
    ascending=False
)

C:\Users\RESHMA J\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pandas\core\nanops.py:1028: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

                    Sharpe
Axis Bluechip     0.047781
Nippon Large Cap -1.585696
Kotak Bluechip   -1.642625
SBI Bluechip     -3.263690
ICICI Bluechip         NaN

In [ ]:
rf = 0.065

In [ ]:
cagr_table = pd.DataFrame(index=nav_pivot.columns)

for fund in nav_pivot.columns:
    cagr_table.loc[fund, '1Y CAGR'] = cagr(nav_pivot[fund], 1)
    cagr_table.loc[fund, '3Y CAGR'] = cagr(nav_pivot[fund], 3)
    cagr_table.loc[fund, '5Y CAGR'] = cagr(nav_pivot[fund], 5)

cagr_table = cagr_table * 100
cagr_table.round(2)

                  1Y CAGR  3Y CAGR  5Y CAGR
scheme_name
Axis Bluechip        0.17     0.18     0.26
ICICI Bluechip      -0.54    -0.17    -0.59
Kotak Bluechip       1.97     3.20     2.91
Nippon Large Cap    -0.54    -0.01    -0.50
SBI Bluechip         0.16     0.08    -1.15

In [ ]:
import pandas as pd
import numpy as np

def cagr(series, years):
    series = series.dropna()

    if len(series) < years * 12:  # monthly data
        return np.nan

    start = series.iloc[-years*12]
    end = series.iloc[-1]

    return (end/start)**(1/years) - 1

In [ ]:
print(nav_pivot.shape)
print(returns.shape)

(3621, 5)
(3621, 5)

In [ ]:
nav_pivot.to_csv("clean_nav_data.csv")
returns.to_csv("fund_returns.csv")

In [ ]:
returns.max()

scheme_name
Axis Bluechip       99.042353
ICICI Bluechip            inf
Kotak Bluechip       0.070446
Nippon Large Cap     0.070415
SBI Bluechip         0.128260
dtype: float64

In [ ]:
returns.describe()

C:\Users\RESHMA J\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pandas\core\nanops.py:1028: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

scheme_name,Axis Bluechip,ICICI Bluechip,Kotak Bluechip,Nippon Large Cap,SBI Bluechip
count,3510.000000,2999.000000,2989.000000,2981.000000,2867.000000
mean,0.028475,inf,0.000662,0.000583,-0.000060
std,1.671731,NaN,0.010028,0.010560,0.005813
min,-0.005415,-1.000000,-0.100119,-0.129512,-0.113092
25%,0.000174,-0.004044,-0.003359,-0.004360,-0.000018
50%,0.000218,0.000880,0.000808,0.001092,0.000253
75%,0.000296,0.005702,0.005401,0.006226,0.000578
max,99.042353,inf,0.070446,0.070415,0.128260

In [ ]:
returns = nav_pivot.pct_change()

returns.head()

scheme_name,Axis Bluechip,ICICI Bluechip,Kotak Bluechip,Nippon Large Cap,SBI Bluechip
date,,,,,
2012-12-31,NaN,NaN,NaN,NaN,NaN
2013-01-01,0.000246,NaN,NaN,NaN,NaN
2013-01-02,0.000238,NaN,NaN,NaN,NaN
2013-01-03,0.000233,0.003221,NaN,0.002300,0.000240
2013-01-04,0.000229,-0.000232,NaN,0.004969,0.000304

In [ ]:
nav_pivot = clean_nav.pivot_table(
    index='date',
    columns='scheme_name',
    values='nav'
).sort_index()

print(nav_pivot.shape)

(3466, 5)

In [ ]:
clean_nav.groupby('scheme_name')['nav'].agg(['min','max'])

                       min       max
scheme_name
Axis Bluechip      23.9920   30.2219
ICICI Bluechip     13.6318  113.6849
Kotak Bluechip     30.5643  281.1083
Nippon Large Cap   12.2191  106.1272
SBI Bluechip      102.2299  161.3775

In [ ]:
clean_nav[
    clean_nav['scheme_name']=='Axis Bluechip'
].groupby('scheme_name')['nav'].agg(['min','max'])

                  min      max
scheme_name
Axis Bluechip  23.992  30.2219

In [ ]:
clean_nav = nav_df.copy()

mask = (
    (clean_nav['scheme_name'] == 'Axis Bluechip') &
    (clean_nav['nav'] > 500)
)

clean_nav.loc[mask, 'nav'] = (
    clean_nav.loc[mask, 'nav'] / 100
)

In [ ]:
nav_df[
    (nav_df['scheme_name']=='Axis Bluechip') &
    (nav_df['nav'] > 500)
].sort_values('date').head(20)

             date        nav    scheme_name  scheme_code
12502  01-01-2016  3102.3838  Axis Bluechip       119092
12203  01-01-2017  3341.6261  Axis Bluechip       119092
11901  01-01-2018  3563.7227  Axis Bluechip       119092
11638  01-01-2019  3835.6478  Axis Bluechip       119092
11396  01-01-2020  4154.2506  Axis Bluechip       119092
11151  01-01-2021  4432.2723  Axis Bluechip       119092
10425  01-01-2024  5197.2106  Axis Bluechip       119092
10184  01-01-2025  5602.0594  Axis Bluechip       119092
9941   01-01-2026  6024.7187  Axis Bluechip       119092
12476  01-02-2016  3122.1056  Axis Bluechip       119092
12176  01-02-2017  3360.1553  Axis Bluechip       119092
11875  01-02-2018  3583.3151  Axis Bluechip       119092
11615  01-02-2019  3860.3437  Axis Bluechip       119092
11131  01-02-2021  4442.5021  Axis Bluechip       119092
10890  01-02-2022  4620.5663  Axis Bluechip       119092
10646  01-02-2023  4860.9087  Axis Bluechip       119092
10404  01-02-2024  5227.8426  Axis Bluechip       119092
12452  01-03-2016  3141.1679  Axis Bluechip       119092
12153  01-03-2017  3377.1059  Axis Bluechip       119092
11852  01-03-2018  3601.7600  Axis Bluechip       119092

In [ ]:
daily_returns = nav_pivot.pct_change()

In [ ]:
nav_pivot = clean_nav.pivot_table(
    index='date',
    columns='scheme_name',
    values='nav'
).sort_index()

In [ ]:
clean_nav.isna().sum()

date           0
nav            0
scheme_name    0
scheme_code    0
dtype: int64

In [ ]:
clean_nav = nav_df.copy()

clean_nav.loc[
    clean_nav['scheme_name']=='Axis Bluechip',
    'nav'
] = clean_nav.loc[
    clean_nav['scheme_name']=='Axis Bluechip',
    'nav'
].where(
    clean_nav['nav'] < 500,
    None
)

clean_nav.loc[
    clean_nav['nav'] <= 0,
    'nav'
] = None

In [ ]:
nav_df[
    (nav_df['scheme_name']=='ICICI Bluechip') &
    (nav_df['nav'] == 0)
].head(20)

            date  nav     scheme_name  scheme_code
6478  07-04-2013  0.0  ICICI Bluechip       120503

In [ ]:
nav_df[
    (nav_df['scheme_name']=='Axis Bluechip') &
    (nav_df['nav'] > 500)
].sort_values('date').head(20)

             date        nav    scheme_name  scheme_code
12502  01-01-2016  3102.3838  Axis Bluechip       119092
12203  01-01-2017  3341.6261  Axis Bluechip       119092
11901  01-01-2018  3563.7227  Axis Bluechip       119092
11638  01-01-2019  3835.6478  Axis Bluechip       119092
11396  01-01-2020  4154.2506  Axis Bluechip       119092
11151  01-01-2021  4432.2723  Axis Bluechip       119092
10425  01-01-2024  5197.2106  Axis Bluechip       119092
10184  01-01-2025  5602.0594  Axis Bluechip       119092
9941   01-01-2026  6024.7187  Axis Bluechip       119092
12476  01-02-2016  3122.1056  Axis Bluechip       119092
12176  01-02-2017  3360.1553  Axis Bluechip       119092
11875  01-02-2018  3583.3151  Axis Bluechip       119092
11615  01-02-2019  3860.3437  Axis Bluechip       119092
11131  01-02-2021  4442.5021  Axis Bluechip       119092
10890  01-02-2022  4620.5663  Axis Bluechip       119092
10646  01-02-2023  4860.9087  Axis Bluechip       119092
10404  01-02-2024  5227.8426  Axis Bluechip       119092
12452  01-03-2016  3141.1679  Axis Bluechip       119092
12153  01-03-2017  3377.1059  Axis Bluechip       119092
11852  01-03-2018  3601.7600  Axis Bluechip       119092

In [ ]:
print(nav_df.groupby('scheme_name')['nav'].agg(['min','max','count']))

                       min        max  count
scheme_name
Axis Bluechip      23.9920  6158.9665   3566
ICICI Bluechip      0.0000   113.6849   3308
Kotak Bluechip     30.5643   281.1083   3302
Nippon Large Cap   12.2191   106.1272   3299
SBI Bluechip      102.2299   161.3775   3237

In [ ]:
nav_df.groupby('scheme_name')['nav'].agg(['min','max'])

                       min        max
scheme_name
Axis Bluechip      23.9920  6158.9665
ICICI Bluechip      0.0000   113.6849
Kotak Bluechip     30.5643   281.1083
Nippon Large Cap   12.2191   106.1272
SBI Bluechip      102.2299   161.3775

In [ ]:
nav_df.sort_values(['scheme_name','date']).tail(20)

            date       nav   scheme_name  scheme_code
1149  31-08-2021  143.7984  SBI Bluechip       119551
662   31-08-2023  113.9005  SBI Bluechip       119551
3035  31-10-2013  103.3858  SBI Bluechip       119551
2799  31-10-2014  112.5490  SBI Bluechip       119551
2076  31-10-2017  149.1660  SBI Bluechip       119551
1833  31-10-2018  146.7339  SBI Bluechip       119551
1594  31-10-2019  152.3324  SBI Bluechip       119551
867   31-10-2022  107.2729  SBI Bluechip       119551
623   31-10-2023  114.7532  SBI Bluechip       119551
380   31-10-2024  107.8015  SBI Bluechip       119551
139   31-10-2025  109.6768  SBI Bluechip       119551
2995  31-12-2013  103.3941  SBI Bluechip       119551
2759  31-12-2014  115.0256  SBI Bluechip       119551
2518  31-12-2015  125.2020  SBI Bluechip       119551
1795  31-12-2018  149.9206  SBI Bluechip       119551
1553  31-12-2019  153.7054  SBI Bluechip       119551
1308  31-12-2020  160.8071  SBI Bluechip       119551
1067  31-12-2021  120.9424  SBI Bluechip       119551
341   31-12-2024  102.4261  SBI Bluechip       119551
98    31-12-2025  110.3212  SBI Bluechip       119551

In [ ]:
print(nav_df['scheme_name'].unique())

<StringArray>
[    'SBI Bluechip',   'ICICI Bluechip', 'Nippon Large Cap',
    'Axis Bluechip',   'Kotak Bluechip']
Length: 5, dtype: str

In [ ]:
print("Unique Funds:", nav_df['scheme_name'].nunique())

Unique Funds: 5

In [ ]:
nav_df.shape

(16712, 4)

In [ ]:
print("Number of funds:", nav_df['scheme_name'].nunique())

Number of funds: 5

In [ ]:
nav_df[
    nav_df['scheme_name'] == 'Axis Bluechip'
].sort_values('date').head(20)

             date        nav    scheme_name  scheme_code
13408  01-01-2013    23.9979  Axis Bluechip       119092
13104  01-01-2014    26.2235  Axis Bluechip       119092
12803  01-01-2015    28.6160  Axis Bluechip       119092
12502  01-01-2016  3102.3838  Axis Bluechip       119092
12203  01-01-2017  3341.6261  Axis Bluechip       119092
11901  01-01-2018  3563.7227  Axis Bluechip       119092
11638  01-01-2019  3835.6478  Axis Bluechip       119092
11396  01-01-2020  4154.2506  Axis Bluechip       119092
11151  01-01-2021  4432.2723  Axis Bluechip       119092
10425  01-01-2024  5197.2106  Axis Bluechip       119092
10184  01-01-2025  5602.0594  Axis Bluechip       119092
9941   01-01-2026  6024.7187  Axis Bluechip       119092
13382  01-02-2013    24.1686  Axis Bluechip       119092
12778  01-02-2015    28.8206  Axis Bluechip       119092
12476  01-02-2016  3122.1056  Axis Bluechip       119092
12176  01-02-2017  3360.1553  Axis Bluechip       119092
11875  01-02-2018  3583.3151  Axis Bluechip       119092
11615  01-02-2019  3860.3437  Axis Bluechip       119092
11131  01-02-2021  4442.5021  Axis Bluechip       119092
10890  01-02-2022  4620.5663  Axis Bluechip       119092

In [ ]:
print(nav_pivot.index.min())
print(nav_pivot.index.max())

01-01-2013
31-12-2025

In [ ]:
nav_df['date'] = pd.to_datetime(
    nav_df['date'],
    format='%d-%m-%Y'
)

nav_pivot = nav_df.pivot_table(
    index='date',
    columns='scheme_name',
    values='nav'
).sort_index()

nav_pivot.head()

scheme_name,Axis Bluechip,ICICI Bluechip,Kotak Bluechip,Nippon Large Cap,SBI Bluechip
date,,,,,
2012-12-31,23.9920,NaN,NaN,NaN,NaN
2013-01-01,23.9979,NaN,NaN,NaN,NaN
2013-01-02,24.0036,15.0253,NaN,14.6967,103.0059
2013-01-03,24.0092,15.0737,NaN,14.7305,103.0306
2013-01-04,24.0147,15.0702,NaN,14.8037,103.0619

In [ ]:
nav_pivot = nav_df.pivot_table(
    index='date',
    columns='scheme_name',
    values='nav'
)

nav_pivot = nav_pivot.sort_index()

print(nav_pivot.shape)
nav_pivot.head()

(3621, 5)

scheme_name,Axis Bluechip,ICICI Bluechip,Kotak Bluechip,Nippon Large Cap,SBI Bluechip
date,,,,,
2012-12-31,23.9920,NaN,NaN,NaN,NaN
2013-01-01,23.9979,NaN,NaN,NaN,NaN
2013-01-02,24.0036,15.0253,NaN,14.6967,103.0059
2013-01-03,24.0092,15.0737,NaN,14.7305,103.0306
2013-01-04,24.0147,15.0702,NaN,14.8037,103.0619

In [ ]:
nav_pivot = nav_df.pivot_table(
    index='date',
    columns='scheme_name',
    values='nav'
)

nav_pivot = nav_pivot.sort_index()

print(nav_pivot.shape)
nav_pivot.head()

(3621, 5)

scheme_name,Axis Bluechip,ICICI Bluechip,Kotak Bluechip,Nippon Large Cap,SBI Bluechip
date,,,,,
2012-12-31,23.9920,NaN,NaN,NaN,NaN
2013-01-01,23.9979,NaN,NaN,NaN,NaN
2013-01-02,24.0036,15.0253,NaN,14.6967,103.0059
2013-01-03,24.0092,15.0737,NaN,14.7305,103.0306
2013-01-04,24.0147,15.0702,NaN,14.8037,103.0619

In [ ]:
nav_df = pd.read_sql(
    """
    SELECT date,
           nav,
           scheme_name,
           scheme_code
    FROM nav_history
    """,
    conn
)

print(nav_df.columns)
print(nav_df['scheme_code'].nunique())

Index(['date', 'nav', 'scheme_name', 'scheme_code'], dtype='str')
5

In [ ]:
print(nav_df['scheme_name'].unique())

<StringArray>
[    'SBI Bluechip',   'ICICI Bluechip', 'Nippon Large Cap',
    'Axis Bluechip',   'Kotak Bluechip']
Length: 5, dtype: str

In [ ]:
print(nav_df.shape)
print(nav_df['scheme_code'].nunique())

(16712, 4)
5

In [ ]:
print(nav_df.shape)
print(nav_df['scheme_code'].nunique())

(16712, 4)
5

In [ ]:
import pandas as pd
import numpy as np

nav_data['date'] = pd.to_datetime(nav_data['date'])
nav_data = nav_data.sort_values(['amfi_code', 'date'])

nav_data['daily_return'] = nav_data.groupby('amfi_code')['nav'].pct_change()

# validate
nav_data.dropna(subset=['daily_return'], inplace=True)

# sanity check distribution
print(nav_data['daily_return'].describe())

NameError: name 'nav_data' is not defined